package app.services;
// Generated 29/09/2018 11:34:54 PM by Hibernate Tools 4.3.1



/**
 * Series generated by hbm2java
 */
public class Series  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int rate;
     private int episodes;
     private String malImg;
     private String malLink;

    public Series() {
    }

    public Series(String name, int rate, int episodes, String malImg, String malLink) {
       this.name = name;
       this.rate = rate;
       this.episodes = episodes;
       this.malImg = malImg;
       this.malLink = malLink;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getRate() {
        return this.rate;
    }
    
    public void setRate(int rate) {
        this.rate = rate;
    }
    public int getEpisodes() {
        return this.episodes;
    }
    
    public void setEpisodes(int episodes) {
        this.episodes = episodes;
    }
    public String getMalImg() {
        return this.malImg;
    }
    
    public void setMalImg(String malImg) {
        this.malImg = malImg;
    }
    public String getMalLink() {
        return this.malLink;
    }
    
    public void setMalLink(String malLink) {
        this.malLink = malLink;
    }




}


